pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                // Put Go build cache in a writable folder
                GOCACHE = "${WORKSPACE}/.gocache"
            }
            steps {
                // Make sure cache dir exists
                sh 'mkdir -p "$GOCACHE"'

                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
