pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                // Go build cache (already OK now)
                GOCACHE   = "${WORKSPACE}/.gocache"
                // Go module cache (instead of /go/pkg/mod)
                GOMODCACHE = "${WORKSPACE}/.gomodcache"
            }
            steps {
                // Ensure caches exist and are writable
                sh 'mkdir -p "$GOCACHE" "$GOMODCACHE"'

                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                       npm ci
                       npm test
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }
}
